insert into department (name) values ('Product Management');
insert into department (name) values ('Marketing');
insert into department (name) values ('Sales');
insert into department (name) values ('Services');
insert into department (name) values ('Research and Development');
insert into department (name) values ('Support');
insert into department (name) values ('Legal');
insert into department (name) values ('Engineering');
insert into department (name) values ('Accounting');
insert into department (name) values ('Training');
insert into department (name) values ('Human Resources');
insert into department (name) values ('Business Development');
